#! /bin/sh
#
#Dichiaro variabili:
pid_server=`pgrep web_server`

if [ $# -eq 0 ] 
then
	echo Usage: $0 [start\|restart\|stop\|clear]
	echo
	echo start: makes the server run
	echo restart: first stop the server then runs it again
	echo stop: shutdown the server
	echo clear: clear web server cache, server\'s root directory must be specified
else
	if [ X"start" = X$1 ]; 
	then 
		if [ X"$pid_server" = X"" ]
		then
			echo Launching the server ...
			/opt/tvs/web_server &
			echo Done!
		else
			echo Server alredy running!
		fi
	fi
	if [ X"restart" = X$1 ]
	then 
		if [ X"$pid_server" = X"" ]
		then 
			echo Server not running.
			echo Server will now be launched.
			/opt/tvs/web_server &
			echo Done!
		else
			echo Stopping the server ...
			kill $pid_server
			echo Done!
			echo Launching the server ...
			/opt/tvs/web_server &
			echo Done!
		fi
	fi
	if [ X"stop" = X$1 ]
	then
		if [ X"$pid_server" = X"" ]
		then 
			echo Server not running.
		else
			echo Stopping the server ...
			kill $pid_server
			echo Done!
		fi	
	fi
	if [ X"clear" = X$1 ]
	then
		if [ $# != 2 ]
		then
			echo "Server's Root MUST be specified"
		else
			echo Clearing Cahce ...
			sudo rm -rf -v $2/CACHE/*
			echo Done!
		fi
	fi
fi
exit
